# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java Deploy with Maven

on:
  push:
    branches: [ master ]
    tags: [release-v*]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: 缓存 Maven 依赖
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 编译代码
        run: mvn compile
      - name: Deploy the JAR file to the remote server
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate the package
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true
      - name: 查看路径
        run: ifconfig
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref)
        with:
          files: "target/challengeanswerservice-0.0.1-SNAPSHOT.jar"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}


      - name: Deploy to Server # 第二步，rsync推文件
        uses: appleboy/scp-action@master # 使用别人包装好的步骤镜像
        env:
          KEY: ${{ secrets.DEPLOY_KEY }} # 引用配置，SSH私钥
          PORT: "22" # SSH端口
          USERNAME: ${{ secrets.USERNAME }} # 引用配置，服务器登录名
          HOST: ${{ secrets.HOST }} # 引用配置，服务器的host名（IP或者域名domain.com）
        with:
          target: /home/ca/test   # 要推送的文件夹，路径相对于代码仓库的根目录
          source: target/challengeanswerservice-0.0.1-SNAPSHOT.jar # 部署到目标文件夹


      - name: Deploy
        uses: appleboy/ssh-action@master # 使用ssh链接服务器
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PWD }}
          port: ${{ secrets.PORT }}
          script: | # 执行命令（运行到服务器）cd：要确保服务器有这个目录； wget：下载上一步的release到服务器； tar：解压； 安装依赖；启动服务
            cd /home/ca/test
            nohup java -jar challengeanswerservice-0.0.1-SNAPSHOT.jar

#      - name: Push Docker
#        run: |
#          docker login --username=${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }} registry.cn-shanghai.aliyuncs.com
#          docker build . -t ${{ secrets.REGISTRY }}:$GITHUB_RUN_NUMBER
#          docker push ${{ secrets.REGISTRY }}:$GITHUB_RUN_NUMBER
#          docker tag $(docker images ${{ secrets.REGISTRY }}:$GITHUB_RUN_NUMBER -q) ${{ secrets.REGISTRY }}:latest
#          docker push ${{ secrets.REGISTRY }}:latest
#
#
#
#
#  pull-docker:
#    needs: [build]
#    name: Pull Docker
#    runs-on: ubuntu-latest
#    steps:
#      - name: Deploy
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USER }}
#          password: ${{ secrets.PWD }}
#          port: ${{ secrets.PORT }}
#          script: |
#            docker stop $(docker ps --filter ancestor=${{ secrets.REGISTRY }} -q)
#            docker rm -f $(docker ps -a --filter ancestor=${{ secrets.REGISTRY }}:latest -q)
#            docker rmi -f $(docker images  ${{ secrets.REGISTRY }}:latest -q)
#            docker login --username=${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }} registry.cn-shanghai.aliyuncs.com
#            docker pull ${{ secrets.REGISTRY }}:latest
#            docker run -d -p 8060:8060 ${{ secrets.REGISTRY }}:latest
## 上面暴露出了 8060端口, 填你项目端口即可 (没有端口可忽略)
#
#
#
